version: '3.8'

services:
  similar-company-finder:
    build: .
    container_name: similar-company-finder-crew
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - TARGET_COMPANY=${TARGET_COMPANY}
      - OUR_PRODUCT=${OUR_PRODUCT}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CREWAI_TELEMETRY_OPT_OUT=true
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    # Uncomment the following lines if you want to expose a web interface
    # ports:
    #   - "8000:8000"
